
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/valid?createDatabaseIfNotExist=true&autoConnect=true
    username: root
    password: tiger
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
  application:
    name: spring_validator-app
      
server:
  port: 8094  